"""empty message

Revision ID: 122fdf476d4c
Revises: None
Create Date: 2016-04-14 21:08:51.527483

"""

# revision identifiers, used by Alembic.
revision = '122fdf476d4c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
